### ISSUE TITLE
As of recent I am getting: Fatal error: object is not a function

### ISSUE THREAD

**Issue by jestersimpps** [claudetech/grunt-i18n-static#1]
I haven't been able to pinpoint the exact problem yet, but I am recieving the following error in my build since last week:

Running "i18n:dist" (i18n) task
Fatal error: object is not a function

**Comment by danhper** [comment]
I have not updated this package for a while, so maybe something changed in an update of Grunt or something, I am going to check it out

**Comment by danhper** [comment]
The issue came from an API change in [i18next](http://i18next.com/). The version was supposed  to be locked, so I am not really sure why it broke though.
Anyway, this should be fixed in 0.1.10, let me know if you have any issue after upgrading.
