### ISSUE TITLE
Bumping package dependencies breaks functionality for selector '[translate]'

### ISSUE THREAD

**Issue by mobinni** [claudetech/grunt-i18n-static#2]
at version 0.1.9 it throws an error unknown object when I set the selector to '[translate]'

**Comment by danhper** [comment]
I am going to check it out, thanks for reporting.

**Comment by danhper** [comment]
I think it is the same issue as #1, which is due to a change in [i18next](http://i18next.com/) API.
It should be fixed in 0.10, could you try updating?

**Comment by mobinni** [comment]
It works! Thanks very much.

**Comment by danhper** [comment]
Great :+1:
