### ISSUE TITLE
"staticI18n.processDir()" doesn't execute properly

### ISSUE THREAD

**Issue by hiulit** [claudetech/grunt-i18n-static#5]
Hi,

I've just picked up an old project and updated all the dependencies in my `package.json` and suddenly your grunt task stop working properly.

Actually, the task works just fine. It creates the new translated files but it stops executing the next tasks.

What I found is that `staticI18n.processDir` returns a `promise` (created by [promisify-node](https://www.npmjs.com/package/promisify-node)) but your code doesn't expect a `promise`. It passes a function as a callback instead. And that's why `staticI18n.processDir` never executes.

Here's my solution:

```js
staticI18n.processDir options.baseDir, options
    .then done, (err) ->
        grunt.log.error 'Failed to compile: #{err}'
        grunt.fail.warn 'i18n task failed'
```

That's working for me now.

**Comment by hiulit** [comment]
Actually, I don't know if the promise is created by [promisify-node](https://www.npmjs.com/package/promisify-node) or by a `promisify` used internally in `static-i18n` itself.

Also, I don't know if the function will ever show the error messages if it eventually fails.

**Comment by danhper** [comment]
Hi, thanks for reporting. I indeed have not used the grunt plugin in a while.
The error handling part should probably be something like
`.then(done).catch((err) -> ....)`
Would you mind sending a PR with your fix please, so I can publish it on npm?
Thanks!
